---
- name: Копирование Dockerfile
  copy:
    src: "{{ playbook_dir }}/../Dockerfile" # Теперь Ansible будет искать Dockerfile на один уровень выше, чем ansible/playbook.yml
    dest: /home/al/Dockerfile # Это путь, куда Dockerfile будет скопирован на целевом сервере. Убедитесь, что он существует и доступен для пользователя 'al'.

- name: Копирование cowrie.cfg
  ansible.builtin.template:
    src: config.cfg.j2
    dest: /home/ubuntu/cowrie.cfg

- name: Запуск контейнера honeypot
  ansible.builtin.shell: |
    docker build -t honeypot .
    docker run -d --name honeypot -p {{ honeypot_port }}:2222 honeypot
