---
- name: Копирование Dockerfile
  ansible.builtin.copy:
    src: Dockerfile
    dest: /tmp/Dockerfile

- name: Копирование cowrie.cfg
  ansible.builtin.template:
    src: config.cfg.j2
    dest: /home/ubuntu/cowrie.cfg

- name: Запуск контейнера honeypot
  ansible.builtin.shell: |
    docker build -t honeypot .
    docker run -d --name honeypot -p {{ honeypot_port }}:2222 honeypot
