pipeline {
    agent any
    stages {
        stage('Клонирование репозитория') {
            steps {
                git branch: 'main', url: 'https://github.com/3965820git/honeypot-automation.git' // ИЛИ 'master', если ваша ветка master
            }
        }
        stage('Линт и тесты') {
            steps {
                sh 'ansible-playbook --syntax-check ansible/playbook.yml'
                sh 'ansible-playbook --check ansible/playbook.yml -i ansible/inventory'
            }
        }
        stage('Развертывание Honeypot') {
            steps {
                sh 'ansible-playbook ansible/playbook.yml -i ansible/inventory'
            }
        }
    }
}
